name: Create Preview Builds For Android and iOS

jobs:
  build_android:
    name: Build Android Preview
    type: build
    params:
      platform: android
      profile: preview

  build_ios:
    name: Build iOS Preview
    type: build
    params:
      platform: ios
      profile: preview
      refresh_ad_hoc_provisioning_profile: true