name: E2E Android

jobs:
  build_android_for_e2e:
    name: Build Android E2E APK
    type: build
    params:
      platform: android
      profile: e2e-test

  maestro_test:
    name: Run FinniApp E2E
    needs: [build_android_for_e2e]
    type: maestro
    params:
      build_id: ${{ needs.build_android_for_e2e.outputs.build_id }}
      flow_path: ['.maestro/smoke-financial.yml', '.maestro/google-drive-boundary.yml']
