import { StyleSheet } from 'react-native';

import { Fonts, LayoutTokens } from '@/constants/theme';

export const styles = StyleSheet.create({
  formShell: { flex: 1 },
  formFooter: { borderTopWidth: StyleSheet.hairlineWidth, paddingHorizontal: 20, paddingTop: 10 },
  footerButton: { marginTop: 0 },
  container: {
    padding: 20,
    gap: 8,
    paddingBottom: LayoutTokens.formScrollBottom,
  },
  formRemainder: {
    gap: 8,
  },
  label: {
    marginTop: 8,
    marginBottom: 4,
    fontWeight: '600',
  },
  input: {
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 12,
    fontSize: 16,
    fontFamily: Fonts.regular,
  },
  nameSuggestions: {
    borderWidth: 1,
    borderRadius: 8,
    overflow: 'hidden',
    marginTop: -2,
  },
  nameSuggestionsLabel: {
    fontSize: 12,
    fontWeight: '600',
    opacity: 0.6,
    paddingHorizontal: 12,
    paddingTop: 9,
    paddingBottom: 4,
  },
  nameSuggestion: {
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  shareSection: {
    gap: 8,
    marginBottom: 4,
    paddingVertical: 8,
  },
  shareToggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  shareToggleCopy: {
    flex: 1,
    gap: 3,
  },
  shareLabel: {
    fontSize: 14,
    fontWeight: '600',
  },
  shareDescription: {
    fontSize: 12,
    opacity: 0.65,
  },
  shareOptions: {
    flexDirection: 'row',
    gap: 8,
  },
  shareButton: {
    flex: 1,
    alignItems: 'center',
    borderWidth: 1,
    borderRadius: 8,
    paddingVertical: 9,
  },
  shareButtonSelected: {
    borderColor: '#0B315B',
    backgroundColor: '#20C9B51F',
  },
  shareButtonTextSelected: {
    color: '#0B315B',
    fontWeight: '700',
  },
  shareResult: {
    color: '#0B315B',
    fontSize: 14,
    fontWeight: '600',
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 8,
    backgroundColor: '#20C9B51F',
  },
  manualPercentageLabel: {
    flex: 1,
    fontSize: 14,
    fontWeight: '600',
  },
  manualPercentageRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginTop: 2,
  },
  exactAmountField: {
    gap: 7,
    marginTop: 2,
  },
  exactAmountInput: {
    width: '100%',
  },
  percentageInputContainer: {
    width: 120,
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 12,
  },
  percentageInput: {
    flex: 1,
    fontSize: 16,
    paddingVertical: 9,
  },
  percentageSuffix: {
    fontSize: 16,
    fontWeight: '600',
    opacity: 0.7,
  },
  selectButton: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 13,
    gap: 12,
  },
  selectPressed: { opacity: 0.7 },
  selectValue: { flexDirection: 'row', alignItems: 'center', gap: 10, flex: 1 },
  selectDot: { width: 14, height: 14, borderRadius: 5 },
  selectOverlay: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(0,0,0,0.45)' },
  selectSheet: { maxHeight: '72%' },
  selectContent: { borderTopLeftRadius: 18, borderTopRightRadius: 18, padding: 20, gap: 14 },
  selectHandle: { width: 38, height: 4, borderRadius: 2, backgroundColor: '#60758E', opacity: 0.55, alignSelf: 'center' },
  selectOptions: { maxHeight: 390 },
  selectOption: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderWidth: 1, borderRadius: 10, paddingHorizontal: 12, paddingVertical: 13, marginBottom: 8, gap: 12 },
  selectOptionSelectedText: { fontWeight: '700' },
  selectClose: { borderWidth: 1, borderRadius: 10, paddingVertical: 13, alignItems: 'center' },
  paymentHint: {
    fontSize: 13,
    lineHeight: 18,
    paddingHorizontal: 4,
    opacity: 0.9,
  },
  dateButton: {
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  doneDate: {
    alignSelf: 'flex-end',
  },
  button: {
    marginTop: 16,
    backgroundColor: '#0B315B',
    borderRadius: 10,
    paddingVertical: 14,
    alignItems: 'center',
  },
  buttonDisabled: {
    opacity: 0.6,
  },
  buttonText: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 16,
  },
  recurringBox: {
    borderWidth: 1,
    borderRadius: 10,
    marginTop: 10,
    overflow: 'hidden',
  },
  installmentBox: {
    borderWidth: 1,
    borderRadius: 12,
    marginTop: 14,
    overflow: 'hidden',
  },
  installmentHeader: {
    minHeight: 76,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  installmentBody: {
    borderTopWidth: 1,
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 18,
    gap: 14,
  },
  installmentSectionLabel: { fontWeight: '700', marginTop: 4 },
  customInstallments: { gap: 7 },
  customInstallmentsLabel: { fontSize: 13, fontWeight: '600', opacity: 0.75 },
  customInstallmentInput: { marginTop: 0 },
  recurringHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 13,
  },
  recurringHeaderCopy: { flex: 1, gap: 2 },
  recurringFields: { borderTopWidth: 1, padding: 13 },
  recurringExpenseActions: { gap: 8, marginTop: 10 },
  savingsHint: { fontSize: 13, lineHeight: 18, opacity: 0.68 },
  secondaryAction: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderWidth: 1,
    borderRadius: 10,
    padding: 12,
  },
  deleteButton: {
    marginTop: 8,
    borderWidth: 1,
    borderColor: '#C93F4B',
    borderRadius: 10,
    paddingVertical: 13,
    alignItems: 'center',
  },
  deleteButtonText: {
    color: '#C93F4B',
    fontWeight: '700',
  },
});
